on: [push]

jobs:
  validate_openapi:
    runs-on: ubuntu-latest
    name: Validate OpenAPI definitions
    env:
      NODE_OPTIONS: --no-deprecation # Redocly uses deprecated `punycode` package, but that shouldn't be an issue.
    steps:
      - uses: actions/checkout@v2
      - name: Install OpenAPI validator
        run: npm install @redocly/cli
      - name: Validate definitions
        run: openapi lint Swagger/*.yaml
