on: [push]

jobs:
  validate_openapi:
    runs-on: ubuntu-latest
    name: Validate OpenAPI definitions
    steps:
      - uses: actions/checkout@v4
      - name: Validate definitions
        run: npx --no-deprecation @redocly/cli lint Swagger/*.yaml
