on: [push]

jobs:
  validate_openapi:
    runs-on: ubuntu-latest
    name: Validate OpenAPI definitions

    steps:
      - uses: actions/checkout@v2
      - uses: mbowman100/swagger-validator-action@master
        with:
          files: |
            Swagger/AlpacaDeviceAPI_v1.yaml
            Swagger/AlpacaManagementAPI_v1.yaml
